version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
  - package-ecosystem: "docker"
    directory: /
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
  - package-ecosystem: "cargo"
    directories:
      - /
      - /ruuvi2mqtt-esp32
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
