[package]
name = "ruuvi2mqtt"
version = "1.0.2-dev"
authors = ["Teemu Matilainen <teemu.matilainen@iki.fi>"]
license = "MIT"
homepage = "https://github.com/tmatilai/ruuvi2mqtt"
repository = "https://github.com/tmatilai/ruuvi2mqtt"
edition = "2021"

[profile.release]
lto = true
# TODO: enable when Cargo 1.59 is installed by default
#strip = true

[dependencies]
anyhow = "1.0"
btleplug = "0.9.0"
clap = { version = "3.1.15", features = ["derive", "env"] }
derivative = "2.2.0"
env_logger = "0.9.0"
futures = "0.3.19"
log = "0.4.14"
rand = "0.8.4"
rumqttc = "0.10.0"
ruuvi-sensor-protocol = "0.5.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.78"
serde_with = "1.12.0"
serde_yaml = "0.8.23"
sysinfo = "0.23.0"
tokio = { version = "1.16.1", features = ["macros", "rt-multi-thread"] }
