[target.aarch64-unknown-linux-gnu]
image = "ghcr.io/tmatilai/rustcross:dbus-aarch64-gnu-1.1.1"

[target.armv7-unknown-linux-gnueabihf]
image = "ghcr.io/tmatilai/rustcross:dbus-armv7-gnu-1.1.1"

[build.env]
passthrough = [
    "RUSTFLAGS",
]
