name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch: {}

jobs:
  build:
    name: Build binaries
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        target:
          - aarch64-unknown-linux-gnu
          - aarch64-unknown-linux-musl
          - armv7-unknown-linux-gnueabihf
          - armv7-unknown-linux-musleabihf
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
        os: [ubuntu-latest]
    env:
      RELEASE: ${{ startsWith(github.ref, 'refs/tags/v') }}
      PROFILE: ${{ startsWith(github.ref, 'refs/tags/v') && 'release' || 'debug' }}
      MUSL: ${{ contains(matrix.target, '-unknown-linux-musl') }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v5.0.0

      - name: Setup | Rust
        uses: dtolnay/rust-toolchain@b3b07ba8b418998c39fb20f53e8b695cdcc8de1b
        with:
          toolchain: stable

      - name: Setup | Cache
        uses: Swatinem/rust-cache@98c8021b550208e191a6a3145459bfc9fb29c4c0 # v2.8.0
        with:
          shared-key: ${{ matrix.target }}-${{ matrix.os }}-${{ env.PROFILE }}-build

      - name: Setup | Cross
        run: |
          cargo install --bins cross

      - name: Setup | Log in to the Container registry
        uses: docker/login-action@v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup | Set build options
        if: env.RELEASE == 'true'
        run: |
          echo 'RELEASE_FLAG=--release' >> $GITHUB_ENV

      - name: Build
        run: cross build --verbose ${{ env.RELEASE_FLAG }} --target ${{ matrix.target }}

      - name: Prepare artifact
        run: |
          mkdir -p 'binaries/${{ matrix.target }}'
          cp target/${{ matrix.target }}/${{ ENV.PROFILE }}/ruuvi2mqtt binaries/${{ matrix.target }}/

      - name: Upload artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: binaries-${{ matrix.target }}
          path: binaries
          if-no-files-found: error
          compression-level: 3

  docker:
    name: Build and push Docker images
    needs: build
    permissions:
      contents: read
      packages: write
    env:
      PLATFORMS: linux/amd64,linux/arm64,linux/arm/v7
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v5.0.0

      - name: Setup | Download artifacts
        uses: actions/download-artifact@v6.0.0
        with:
          pattern: binaries-*
          path: binaries
          merge-multiple: true

      - name: Setup | Prepare binaries
        run: |
          chmod 0755 binaries/*/ruuvi2mqtt
          mkdir -p binaries/{${{ env.PLATFORMS }}}
          ln -s ../../aarch64-unknown-linux-musl/ruuvi2mqtt binaries/linux/arm64/
          ln -s ../../../armv7-unknown-linux-musleabihf/ruuvi2mqtt binaries/linux/arm/v7/
          ln -s ../../x86_64-unknown-linux-musl/ruuvi2mqtt binaries/linux/amd64/

      - name: Setup | Log in to the Container registry
        uses: docker/login-action@v3.6.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup | Docker QEMU
        uses: docker/setup-qemu-action@v3.6.0

      - name: Setup | Docker Buildx
        uses: docker/setup-buildx-action@v3.11.1

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.7.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          platforms: ${{ env.PLATFORMS }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  gh-release:
    name: Make a GitHub release
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Download artifacts
        uses: actions/download-artifact@v6.0.0
        with:
          pattern: binaries-*
          path: binaries
          merge-multiple: true

      - name: Create tarballs
        run: |
          mkdir -p tarballs
          for target in binaries/*; do
            tar -czf tarballs/$(basename $target).tar.gz -C $target .
          done

      - name: Create a Release
        uses: ncipollo/release-action@bcfe5470707e8832e12347755757cec0eb3c22af # v1.18.0
        with:
          draft: true
          artifacts: tarballs/*
          artifactErrorsFailBuild: true
